version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.eclipse.jetty:jetty-runner
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.opensaml:xmltooling
    versions:
    - 1.4.6
  - dependency-name: org.wso2.carbon.identity.inbound.auth.oauth2:org.wso2.carbon.identity.oauth
    versions:
    - 6.2.31
  - dependency-name: org.wso2.carbon.identity.inbound.auth.oauth2:org.wso2.carbon.identity.oauth.common
    versions:
    - 6.2.31
  - dependency-name: org.apache.santuario:xmlsec
    versions:
    - 2.1.4
